install_data(
  'hicolor/scalable/apps/com.cheerschopper.Streaks.svg',
  install_dir: get_option('datadir') / 'icons' / 'hicolor' / 'scalable' / 'apps'
)

install_data(
  'hicolor/symbolic/apps/com.cheerschopper.Streaks-symbolic.svg',
  install_dir: get_option('datadir') / 'icons' / 'hicolor' / 'symbolic' / 'apps'
)
